"""rename address

Revision ID: dabbd75d8533
Revises: 9943001f533f
Create Date: 2024-08-22 01:32:01.257357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabbd75d8533'
down_revision = '9943001f533f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name = 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name = 'address')
    # ### end Alembic commands ###
